DISTRICTS = [
    {
        "id": "tvm",
        "name": "Thiruvananthapuram",
        "river": "Karamana, Neyyar",
        "risk_factor": "Coastal and urban runoff",
        "lat": 8.5241,
        "lon": 76.9366,
        "elevation_m": 10,
        "slope_deg": 3.5,
        "drainage_density": 0.42,
        "urban_fraction": 0.68,
        "distance_to_river_m": 900,
    },
    {
        "id": "kol",
        "name": "Kollam",
        "river": "Kallada",
        "risk_factor": "Ashtamudi lake overflow",
        "lat": 8.8932,
        "lon": 76.6141,
        "elevation_m": 8,
        "slope_deg": 2.8,
        "drainage_density": 0.38,
        "urban_fraction": 0.55,
        "distance_to_river_m": 700,
    },
    {
        "id": "pta",
        "name": "Pathanamthitta",
        "river": "Pamba, Achankovil",
        "risk_factor": "2018 epicentre, dam releases",
        "lat": 9.2648,
        "lon": 76.7870,
        "elevation_m": 40,
        "slope_deg": 6.5,
        "drainage_density": 0.31,
        "urban_fraction": 0.30,
        "distance_to_river_m": 300,
    },
    {
        "id": "alp",
        "name": "Alappuzha",
        "river": "Pamba delta",
        "risk_factor": "Near sea level, backwater flooding",
        "lat": 9.4981,
        "lon": 76.3388,
        "elevation_m": 1,
        "slope_deg": 0.5,
        "drainage_density": 0.20,
        "urban_fraction": 0.48,
        "distance_to_river_m": 50,
    },
    {
        "id": "ktm",
        "name": "Kottayam",
        "river": "Meenachil, Manimala",
        "risk_factor": "Vembanad lake, low-lying terrain",
        "lat": 9.5916,
        "lon": 76.5222,
        "elevation_m": 3,
        "slope_deg": 1.2,
        "drainage_density": 0.28,
        "urban_fraction": 0.42,
        "distance_to_river_m": 250,
    },
    {
        "id": "idk",
        "name": "Idukki",
        "river": "Periyar",
        "risk_factor": "High elevation, reservoir releases",
        "lat": 9.8494,
        "lon": 77.0993,
        "elevation_m": 1200,
        "slope_deg": 18.0,
        "drainage_density": 0.55,
        "urban_fraction": 0.08,
        "distance_to_river_m": 600,
    },
    {
        "id": "ekm",
        "name": "Ernakulam",
        "river": "Periyar, Muvattupuzha",
        "risk_factor": "Dense urban, river confluence",
        "lat": 9.9816,
        "lon": 76.2999,
        "elevation_m": 6,
        "slope_deg": 1.8,
        "drainage_density": 0.35,
        "urban_fraction": 0.78,
        "distance_to_river_m": 400,
    },
    {
        "id": "tsr",
        "name": "Thrissur",
        "river": "Chalakudy, Bharathapuzha",
        "risk_factor": "Low-lying plains, flash floods",
        "lat": 10.5276,
        "lon": 76.2144,
        "elevation_m": 5,
        "slope_deg": 1.5,
        "drainage_density": 0.30,
        "urban_fraction": 0.50,
        "distance_to_river_m": 350,
    },
    {
        "id": "pkd",
        "name": "Palakkad",
        "river": "Bharathapuzha, Kalpathipuzha",
        "risk_factor": "Palakkad Gap wind-driven rain",
        "lat": 10.7867,
        "lon": 76.6548,
        "elevation_m": 100,
        "slope_deg": 4.0,
        "drainage_density": 0.25,
        "urban_fraction": 0.33,
        "distance_to_river_m": 500,
    },
    {
        "id": "mpm",
        "name": "Malappuram",
        "river": "Bharathapuzha, Chaliyar",
        "risk_factor": "Rapid urbanisation, poor drainage",
        "lat": 11.0510,
        "lon": 76.0711,
        "elevation_m": 30,
        "slope_deg": 5.5,
        "drainage_density": 0.27,
        "urban_fraction": 0.45,
        "distance_to_river_m": 450,
    },
    {
        "id": "kkd",
        "name": "Kozhikode",
        "river": "Chaliyar, Kadalundi",
        "risk_factor": "Hilly terrain, landslide risk",
        "lat": 11.2588,
        "lon": 75.7804,
        "elevation_m": 25,
        "slope_deg": 8.5,
        "drainage_density": 0.33,
        "urban_fraction": 0.60,
        "distance_to_river_m": 550,
    },
    {
        "id": "wnd",
        "name": "Wayanad",
        "river": "Kabani, Mananthavady",
        "risk_factor": "Western Ghats, steepest slopes",
        "lat": 11.6854,
        "lon": 76.1320,
        "elevation_m": 900,
        "slope_deg": 22.0,
        "drainage_density": 0.48,
        "urban_fraction": 0.12,
        "distance_to_river_m": 800,
    },
    {
        "id": "knr",
        "name": "Kannur",
        "river": "Valapattanam, Kuppam",
        "risk_factor": "Coastal and riverine combined",
        "lat": 11.8745,
        "lon": 75.3704,
        "elevation_m": 15,
        "slope_deg": 4.2,
        "drainage_density": 0.29,
        "urban_fraction": 0.40,
        "distance_to_river_m": 650,
    },
    {
        "id": "ksd",
        "name": "Kasaragod",
        "river": "Chandragiri, Payaswini",
        "risk_factor": "Northernmost, laterite soil",
        "lat": 12.4996,
        "lon": 74.9869,
        "elevation_m": 20,
        "slope_deg": 5.0,
        "drainage_density": 0.26,
        "urban_fraction": 0.28,
        "distance_to_river_m": 700,
    },
]

DISTRICTS_BY_ID = {d["id"]: d for d in DISTRICTS}
